[package]
name = "keepass-diff"
description = "This CLI-tool reads two Keepass (.kdbx) files and prints their differences."
keywords = ["cli", "diff", "keepass"]
repository = "https://github.com/Narigo/keepass-diff"
license = "MIT"
readme = "README.md"
version = "0.2.0"
authors = ["Joern Bernhardt <joern.bernhardt@googlemail.com>"]

# See https://crates.io/category_slugs
categories = ["command-line-utilities"]

exclude = [
  "docs/*"
]

[dependencies]
clap = "2.32.0"
keepass = "0.3.3"
rpassword = "2.0.0"
termcolor = "1.0.4"
